using System.Collections.Generic;

public static class HighscoreData
{
    public static List<string> DragonNames = new List<string>()
    {
       "Spyro", "Cynder", "Bahamut", "Smaug", "Elliot", "Mushu", "Haku", "Denoith", "Aldewth", "Loryth", "Oesayuth", "Agath", "Cerath", "Morilth", "Samadth", "Banacheth", "Ytath", "Adrothyth", "Awasonth", "Ildaith", "Diestaith", "Angidth", "Ghayth", "Raykeleth", "Aphaeth", "Ghaouth", "Honrodath", "Cialdeeth", "Delcheehth", "Reth", "Aydikth", "Feath", "Ulouth", "Kalulth", "Smildeath", "Denormosth", "Shyachayth", "Leequayth", "Eseath", "Peroth", "Doeenthyth", "Taiemth", "Unddynuith", "Enonth", "Queth", "Ooqarth", "Oofayth", "Voidynuth", "Therenth", "Raykalenth", "Pereuth", "Warkimeeth", "Rotheth", "Untaleeth", "Eaturth", "Eaughuth", "Queloroith", "Ananth", "Radenthath", "Endynoth", "Vesrodusth", "Achith", "Smudth", "Kinorth", "Aeryth", "Umeroth", "Iaduth", "Stirth", "Dynulth", "Oloith", "Tith", "Uisayoth", "Dynoughouth", "Ustumitth", "Tairotheth", "Izeath", "Cairanoth", "Naligth", "Garuth", "Eyweth", "Euestath", "Enith", "Oiburauth", "Ydenylth", "Issath", "Kalaraith", "Ywyth", "Anath", "Etenthilth", "Buryth", "Ewuth", "Urnyth", "Wuith", "Eirobth", "Awardith", "Rothanaith", "Nith", "Banaith", "Usherth", "Eytelth", "Engoth", "Ashexth", "Schachaoth", "Airaith", "Athyth", "Lorath", "Truradeth", "Bairakoth", "Eisuth", "Ghaith", "Saminth", "Lorradenth", "Rheyth", "Awoeth", "Oldoth", "Ezirth", "Kinnysoth", "Sneuth", "Raknysath", "Hith", "Echimuith", "Eldath", "Rakougheth", "Umooth", "Etath", "IpolelthDaroth", "Ageathith", "Llygarotth", "Rothskelorth", "Aeadoth", "Shyanuth", "Haidarufth", "Triaesteth", "Ighttaneth", "Deianolth", "Auneth", "Ennivth", "Emvoroth", "Darath", "Ybelath", "Iekinoth", "Iramth", "Athath", "Voranitth", "Sersulosth", "Lleth", "Enthunth", "Eldouth", "Waraugharth", "Idilth", "Ildusketh", "Ukiath", "Quaolth", "Atiath", "Esseth", "Enendarth", "Echlyeyth", "Shyeth", "Ineolth", "Echinaikth", "Sayrakeath", "Leeth", "Serawoth", "Blath", "Rath", "Ardinaoth", "Edenath", "Honyth", "Uyith", "Kaichaiath", "Rynanosth", "Skeledth", "Yltoth", "Nysaith", "Kith", "Creth", "Queormyth", "Eldskelyth", "Denvorerth", "Euosarth", "Pheyechonth", "Lleytureath", "Tinaleynth", "Imashyth", "Entheth  Emoth", "Oteth", "Iyoth", "Hineuth", "Issith", "Iauth", "Boeth", "Yrdynth", "Deeranylth", "Toreth", "Snoth", "Ueteth", "Ooiaoth", "Rilwaruth", "Nith", "Ysath", "Ayith", "Lyeoldaith", "Cleuireth", "Endyth", "Adraisth", "Antyth", "Zoth", "Asyth", "Estveralth", "Orustiath", "Aldburiath", "Ometh", "Waralth", "Loimosuth", "Oiaughyth", "Euingith", "Datherath", "Ireith", "Ineuth", "Dynaldith", "Ustiath", "Iseth", "Untenthatth", "Ontirth", "Thidth", "Aretath", "Ackeuth", "Yooth", "Darath", "Oecuth", "Chroiurnuth", "Nysdaneth", "Ophuth", "Shylorath", "Atbelezth", "Ardith", "Iepeth", "Meiardenth", "Irdeth", "Tasrayeth", "Sayemoth", "Untubth", "Ipolith"
    };

    public static string[] HighscoreNames = new string[10];

    public static int[] HighscoreValues = new int[10];

}